### ISSUE TITLE
Error running test on windows 10

### ISSUE THREAD

**Issue by romfrolov** [akolotov/qadwallet-testenv#1]
TESTBEDGETH
```

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : 22 January, 2018 12:51:10 PM
   Source : C:\Users\roman\Desktop\qadwallet\chain\data.orig\
     Dest : C:\Users\roman\Desktop\qadwallet\chain\data\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /NP /R:1000000 /W:30

------------------------------------------------------------------------------

          New Dir          0    C:\Users\roman\Desktop\qadwallet\chain\data.orig\
          New Dir          3    C:\Users\roman\Desktop\qadwallet\chain\data.orig\geth\
            New File                   0        LOCK
            New File                  64        nodekey
            New File                 438        transactions.rlp
          New Dir          6    C:\Users\roman\Desktop\qadwallet\chain\data.orig\geth\chaindata\
            New File               52068        000002.ldb
            New File                9427        000003.log
            New File                  16        CURRENT
            New File                   0        LOCK
            New File                1059        LOG
            New File                 218        MANIFEST-000004
          New Dir          5    C:\Users\roman\Desktop\qadwallet\chain\data.orig\geth\lightchaindata\
            New File               83123        000001.log
            New File                  16        CURRENT
            New File                   0        LOCK
            New File                 360        LOG
            New File                  54        MANIFEST-000000
          New Dir          5    C:\Users\roman\Desktop\qadwallet\chain\data.orig\geth\nodes\
            New File              253511        000001.log
            New File                  16        CURRENT
            New File                   0        LOCK
            New File                 437        LOG
            New File                  54        MANIFEST-000000
          New Dir          1    C:\Users\roman\Desktop\qadwallet\chain\data.orig\keystore\
            New File                 491        UTC--2018-01-19T14-02-54.191812380Z--d837adae7b3987461f412c41528ef709bbdad8a8

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         6         6         0         0         0         0
   Files :        20        20         0         0         0         0
   Bytes :   391.9 k   391.9 k         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00


   Speed :             5145538 Bytes/sec.
   Speed :             294.430 MegaBytes/min.
   Ended : 22 January, 2018 12:51:10 PM

The system cannot find the path specified.
```

```
PS C:\Users\roman\Desktop\qadwallet> .\do_tests.cmd "C:\geth\geth.exe" "C:\Users\roman\AppData\Local\Programs\Python\Pyt
hon36\python.exe"
Checking version of web3.py python library...
Test chain is being deployed...
Tests running...
TEST 001: Getting balance, uno.
EXECUTED:
../src/qadwallet.py --key 41358ef24fe86a58d67810e1b3eeeba47473b98e75dcaf9a6c295ff445d6d668
The command executed too long.
FAILED
TEST 002: Getting balance, dos.
EXECUTED:
../src/qadwallet.py --key c96128075e63206192ed8f70484bab090e08feb8ea1caf2e9665d989ab78a3f4
The command executed too long.
FAILED
TEST 003: Getting balance, tres.
EXECUTED:
../src/qadwallet.py --key 56e02f6e0d151d8a9174557d8b9bf5cd347ef1c3891bd4fedbac252d5aa38b90
The command executed too long.
FAILED
TEST 004: Getting balance, cuatro.
EXECUTED:
../src/qadwallet.py --key 61423bbb54c6b8aee380d24954f3c22941020890f67d3305d0957b180f0dc834
The command executed too long.
FAILED
TEST 005: Sending transaction.
Traceback (most recent call last):
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\utils\windows.py", line 17, in __init__
    0, None, win32file.OPEN_EXISTING, 0, None)
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 231, in <module>
    res = test_sending_good_transaction()
  File "test.py", line 98, in test_sending_good_transaction
    new_transaction_filter = web3.eth.filter('pending')
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\eth.py", line 260, in filter
    "eth_newPendingTransactionFilter", [],
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\manager.py", line 98, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\manager.py", line 81, in _make_request
    return request_func(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 152, in make_request
    with self._lock, self._socket as sock:
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 42, in __enter__
    self.sock = self._open()
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 55, in _open
    return get_ipc_socket(self.ipc_path)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 23, in get_ipc_socket
    return NamedPipe(ipc_path)
  File "C:\Users\roman\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\utils\windows.py", line 19, in __init__
    raise IOError(err)
OSError: (2, 'CreateFile', 'The system cannot find the file specified.')
Test chain is shuting down...
```

**Comment by akolotov** [comment]
Should be fixed by https://github.com/akolotov/qadwallet-testenv/commit/13798df4ebe83a33c93cb38548a94e1eaf38985b. Please check.

**Comment by romfrolov** [comment]
Fixed after a new commit.
